# Generated by Django 5.1.4 on 2025-01-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_assignment_category_codequestion_coursecategory_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="course",
            name="introduction_video",
        ),
        migrations.AddField(
            model_name="course",
            name="introduction_video_thumbnail",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="introduction_video_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="storage_type",
            field=models.CharField(
                choices=[("drive", "Google Drive"), ("local", "Local Storage")],
                default="drive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="video_duration",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="video_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="course_images/"),
        ),
        migrations.AlterField(
            model_name="course",
            name="image_storage_type",
            field=models.CharField(
                choices=[("drive", "Google Drive"), ("local", "Local Storage")],
                default="drive",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="level_info",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Expert", "Expert"),
                    ("All Level", "All Level"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
