# Generated by Django 5.1.4 on 2025-01-23 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_course_introduction_video_thumbnail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="image_view_url",
        ),
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(
                related_name="courses", through="api.CourseCategory", to="api.category"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subcategories",
            field=models.ManyToManyField(
                related_name="courses",
                through="api.CourseSubcategory",
                to="api.subcategory",
            ),
        ),
    ]
