# Generated by Django 5.1.4 on 2025-01-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_course_image_view_url_course_categories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image_view_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="level_info",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
