# Generated by Django 5.1.4 on 2025-01-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_course_image_view_url_alter_course_level_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefilemanager",
            name="image_file_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
