# Generated by Django 5.1.4 on 2025-01-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_coursefilemanager_image_file_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefilemanager",
            name="video_file_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
