# Generated by Django 5.1.4 on 2025-01-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_coursefilemanager_video_file_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="introduction_video_thumbnail",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
