# Generated by Django 5.1.3 on 2025-01-24 01:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_course_introduction_video_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntendedLearners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_audience", models.TextField()),
                ("skills_needed", models.TextField()),
                ("learning_outcomes", models.TextField()),
                ("career_goals", models.TextField()),
                ("participation_knowledge", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intended_learners",
                        to="api.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Intended Learners",
                "db_table": "intended_learners",
            },
        ),
        migrations.DeleteModel(
            name="ExtendedLearners",
        ),
    ]
