# Generated by Django 5.1.3 on 2025-01-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_intendedlearners_delete_extendedlearners"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intendedlearners",
            name="participation_knowledge",
        ),
        migrations.AddField(
            model_name="intendedlearners",
            name="participation_encouragement",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AlterField(
            model_name="intendedlearners",
            name="career_goals",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AlterField(
            model_name="intendedlearners",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="intendedlearners",
            name="learning_outcomes",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AlterField(
            model_name="intendedlearners",
            name="skills_needed",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AlterField(
            model_name="intendedlearners",
            name="target_audience",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
